Installatins script added
SRA-VJTI/ROS-Workshop-2.1 pull request #71
Opened 2024-04-08 10:42 UTC by AryanNanda17

This PR resolves issue #30.
The installation script provides a complete installation process for MARIO Workshop, which includes the following steps:-
- Installing esp_idf-v5.1
- Cloning the Mario repository
- Installing ROS2 with additional packages
- Creating a ros2_ws
- Installing Gazebo
- Copying Mario's folders to ros2_ws
- Setting up microros_ws
To do: Adding instructions for building microros_ws in MacOS.

I will verify the installation on both Linux and macOS systems and provide an update soon.

2024-04-09 05:59 UTC, aPR0T0 requested changes

2024-04-09 05:59 UTC, aPR0T0 commented on mario_install.sh
> +    git clone --recursive https://github.com/AryanNanda17/MARIO.git /tmp/ros2_ws
This line clones your fork @AryanNanda17

2024-04-09 05:59 UTC, aPR0T0 commented on mario_install.sh
> +    git clone --recursive https://github.com/AryanNanda17/MARIO.git /tmp/ros2_ws
I will be renaming ros2 branch as humble, so accordingly you have to clone the branch

2024-04-09 05:59 UTC, aPR0T0 commented on mario_install.sh
> +    git clone --recursive https://github.com/AryanNanda17/MARIO.git /tmp/ros2_ws
and why is it cloned in /tmp/ros2_ws?

2024-04-09 05:59 UTC, aPR0T0 commented on mario_install.sh
> +        conda install ros-humble-desktop-full ros-humble-control-* ros-humble-gazebo-ros2-control ros-humble-joint-state-* ros-humble-forward-command-controller ros-humble-robot-state-publisher
ros-humble-control*

we need controller manager as well

2024-04-09 05:59 UTC, aPR0T0 commented on mario_install.sh
> +        conda install ros-humble-desktop-full ros-humble-control-* ros-humble-gazebo-ros2-control ros-humble-joint-state-* ros-humble-forward-command-controller ros-humble-robot-state-publisher
also, add ros-humble-joint-trajectory-controller

2024-04-09 05:59 UTC, aPR0T0 commented on mario_install.sh
> +    mv /tmp/ros2_ws/1_* $HOME/ros2_ws/src
don't do this, just clone in `MARIO` folder

2024-04-09 05:59 UTC, aPR0T0 commented on mario_install.sh
> +        mkdir -p microros_ws/src
clone in the ros2_ws only

2024-04-09 05:59 UTC, aPR0T0 commented on mario_install.sh
> +        mkdir -p microros_ws/src
don't you need to install catkin_pkg and all in macos?

2024-04-09 05:59 UTC, aPR0T0 commented on mario_install.sh
> +        echo "source  ~/ros2_ws/install/setup.bash" >> $HOME/."$_shell_"rc
add alias for sourcing 
`sw = source install/setup.bash

and `get_ros = source /opt/ros/humble/setup.bash`

2024-04-09 15:41 UTC, AryanNanda17 commented on mario_install.sh
> +    git clone --recursive https://github.com/AryanNanda17/MARIO.git /tmp/ros2_ws
Updated it!

2024-04-09 15:51 UTC, aPR0T0 commented
@AryanNanda17 I don't see any commit resolving the bugs

2024-04-09 16:08 UTC, AryanNanda17 commented on mario_install.sh
> +    git clone --recursive https://github.com/AryanNanda17/MARIO.git /tmp/ros2_ws
Do I need to clone just the humble branch or the entire repository?

2024-04-09 16:10 UTC, AryanNanda17 commented on mario_install.sh
> +    git clone --recursive https://github.com/AryanNanda17/MARIO.git /tmp/ros2_ws
The cloning of the repository is temporary as the script will later copy all the folders to both ros2_ws and ros2_ws_firmware.

2024-04-09 16:26 UTC, AryanNanda17 commented on mario_install.sh
> +    mv /tmp/ros2_ws/1_* $HOME/ros2_ws/src
> don't do this, just clone in `MARIO` folder

In the Discord, you advised doing that and not against it. So, should I proceed with copying these folders to the ros2_ws or not?

2024-04-09 16:29 UTC, AryanNanda17 commented on mario_install.sh
> +        echo "source  ~/ros2_ws/install/setup.bash" >> $HOME/."$_shell_"rc
> add alias for sourcing `sw = source install/setup.bash
> 
> and `get_ros = source /opt/ros/humble/setup.bash`

I've included a sourcing command in the terminal to ensure that the specified commands are automatically available whenever the user opens the terminal, this eliminates the need to manually execute them each time.

2024-04-09 16:30 UTC, aPR0T0 commented on mario_install.sh
> +    git clone --recursive https://github.com/AryanNanda17/MARIO.git /tmp/ros2_ws
I think its better to have the MARIO folder in home directory still for future contributors

2024-04-09 16:31 UTC, aPR0T0 commented on mario_install.sh
> +    mv /tmp/ros2_ws/1_* $HOME/ros2_ws/src
You should copy still, just not clone in tmp thing

2024-04-09 16:35 UTC, aPR0T0 requested changes

2024-04-09 16:35 UTC, aPR0T0 commented on mario_install.sh
> +        pip3 install catkin_pkg lark-parser colcon-common-extensions -l rosdep
microros-esp-idf-components depends on this, so its good

2024-04-09 16:35 UTC, aPR0T0 commented on mario_install.sh
> +        git clone -b humble https://github.com/micro-ROS/micro-ROS-Agent.git
have you tested the script with the microros folders in the firmware ?

2024-04-09 17:17 UTC, AryanNanda17 commented on mario_install.sh
> +        git clone -b humble https://github.com/micro-ROS/micro-ROS-Agent.git
I was solving errors since the afternoon. I am not able to setup catkin_pkg in MacOS and I am getting [this](https://pastebin.com/pEmybEe7) error when I try to run colcon build command in ros_ws

2024-04-09 17:53 UTC, aPR0T0 requested changes

2024-04-09 17:53 UTC, aPR0T0 commented on mario_install.sh
> +        git clone -b humble https://github.com/micro-ROS/micro-ROS-Agent.git
pip3 install catkin_pkg lark-parser colcon-common-extensions -l rosdep
        
        isn't it same for mac?

2024-04-09 17:53 UTC, aPR0T0 commented on mario_install.sh
> +    mv ~/ros2_ws/1_* $HOME/ros2_ws/src
shouldn't it be  ~/MARIO/1_* and so on?

2024-04-10 09:59 UTC, AryanNanda17 commented on mario_install.sh
> +    mv ~/ros2_ws/1_* $HOME/ros2_ws/src
Yes, updated it!

2024-04-10 10:11 UTC, AryanNanda17 commented on mario_install.sh
> +        git clone -b humble https://github.com/micro-ROS/micro-ROS-Agent.git
It's the same and I did that but still I am getting same error.

2024-04-10 13:18 UTC, AryanNanda17 commented
@SuperChamp234, could you please try running the installation script? 
- After copying the folders from Mario repo to ros2_ws, the script is doing colcon build, but errors are coming. Could you please help in debugging those errors?

2024-04-10 16:09 UTC, aPR0T0 commented
@AryanNanda17 also, please rename this file to install_codes.sh and remove other shell scripts from previous version of MARIO

2024-04-11 03:07 UTC, SuperChamp234 commented
Hi Aryan, can you ask other team members to run the installation scripts? Both on Linux and Mac. I cannot run as I have an install of ROS for my work running and don’t want to disturb it.

2024-04-11 15:19 UTC, AryanNanda17 commented
I arranged one Linux laptop and verified the installation script on it. 
- 1_chatter_listener:-

[Screencast from 04-11-2024 08:36:03 PM.webm](https://github.com/SRA-VJTI/MARIO/assets/125150482/d2525e91-599f-4955-83b1-90ad21c485a6)
- 2_simulation_dh
![Screenshot from 2024-04-11 20-40-43](https://github.com/SRA-VJTI/MARIO/assets/125150482/02b22570-3ec8-4bfb-9376-e21d819cef56)

- 3_simulation_rviz
![Screenshot from 2024-04-11 20-41-52](https://github.com/SRA-VJTI/MARIO/assets/125150482/5cc61020-a8e7-45d5-946d-83508498e93c)
- 4_simulation_gazebo
![Screenshot from 2024-04-11 20-47-43](https://github.com/SRA-VJTI/MARIO/assets/125150482/10d4ba29-ade0-4a38-86a7-0bfcaca3aaa9)

In 4_simulation_gazebo, I am getting above error.

2024-04-11 15:34 UTC, AryanNanda17 commented
I verified the Installation instructions on MacOS:-
1_chatter_listener:- 
<img width="1421" alt="Screenshot 2024-04-11 at 3 06 04 PM" src="https://github.com/SRA-VJTI/MARIO/assets/125150482/a0ecacf5-68e2-40a6-9511-39fb3303e5ec">

2_simulation_dh:- 
<img width="1439" alt="Screenshot 2024-04-11 at 2 55 54 PM" src="https://github.com/SRA-VJTI/MARIO/assets/125150482/66233b64-ccf7-42e9-a214-2865e1432af2">

3. 3_simulation_rviz:-
<img width="1042" alt="Screenshot 2024-04-11 at 9 02 55 PM" src="https://github.com/SRA-VJTI/MARIO/assets/125150482/70b5e03c-70c3-4407-b552-a67a0fb903e0">
It says to install ```gazebo_ros2_control``` and when I do that using conda and I getting so many conflicts. 
<img width="528" alt="Screenshot 2024-04-11 at 9 04 11 PM" src="https://github.com/SRA-VJTI/MARIO/assets/125150482/e5045f13-d500-4978-95c9-a27082dbac64">

4. 4_simulation_gazebo:-
<img width="1440" alt="Screenshot 2024-04-11 at 8 57 09 PM" src="https://github.com/SRA-VJTI/MARIO/assets/125150482/33c42386-214c-4983-993b-4222c2cd161f">

This is also not working

2024-04-11 15:38 UTC, aPR0T0 commented
![image](https://github.com/SRA-VJTI/MARIO/assets/97826285/43a3a628-62bf-43e6-91c3-73d38260435d)
Install this package as well and try again for simulation_gazebo

2024-04-11 15:40 UTC, aPR0T0 commented
And for linux it might be the same issue that the gazebo-ros package is not installed

for macOS for gazebo-ros2-control what command you used
I am hoping it was sudo mamba install `ros-humble-gazebo-ros2-control`

2024-04-11 15:41 UTC, aPR0T0 commented
@SuperChamp234 please see what's the issue with gazebo-ros2-control

2024-04-11 15:49 UTC, AryanNanda17 commented
> for macOS for gazebo-ros2-control what command you used I am hoping it was sudo mamba install `ros-humble-gazebo-ros2-control`

yes I used  ``` conda install ros-humble-gazebo-ros2-control```

2024-04-11 15:53 UTC, AryanNanda17 commented
> ![image](https://private-user-images.githubusercontent.com/97826285/321693574-43a3a628-62bf-43e6-91c3-73d38260435d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTAyODYsIm5iZiI6MTcxMjg0OTk4NiwicGF0aCI6Ii85NzgyNjI4NS8zMjE2OTM1NzQtNDNhM2E2MjgtNjJiZi00M2U2LTkxYzMtNzNkMzgyNjA0MzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE1Mzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwZDQ1OWY5NDUxZDRjNDRjNjY0YWUyODRhYWYzNDI2MDlkN2ZhYjAyOTdmMmNmZjNiYjFhNDIxMzdlYTE5MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4wUBfY4SbQRQyKlMtm4srkXB_AGCbcsuCwlYo5tzwNg) Install this package as well and try again for simulation_gazebo

I have installed these packages but still getting the same Linux error above.

2024-04-11 16:10 UTC, aPR0T0 commented
@AryanNanda17 send the gazebo error in pastebin

2024-04-11 16:20 UTC, aPR0T0 approved these changes

2024-04-11 16:20 UTC, aPR0T0 commented on installations.sh
> +            sudo apt install -y ros-humble-control-msgs ros-humble-control-toolbox ros-humble-gazebo-ros2-control ros-humble-joint-state-broadcaster ros-humble-joint-state-publisher ros-humble-joint-
Why is gazebo-ros2-control mentioned two times.

2024-04-11 16:20 UTC, aPR0T0 commented on installations.sh
> +            mamba install -n ros_env -y ros-humble-control-msgs ros-humble-control-toolbox ros-humble-joint-state-broadcaster ros-humble-joint-state-publisher ros-humble-joint-state-publisher-gui ros
review the previous comment

2024-04-11 17:08 UTC, AryanNanda17 commented on installations.sh
> +            mamba install -n ros_env -y ros-humble-control-msgs ros-humble-control-toolbox ros-humble-joint-state-broadcaster ros-humble-joint-state-publisher ros-humble-joint-state-publisher-gui ros
Here, it is correct right?

2024-04-11 17:10 UTC, AryanNanda17 commented on installations.sh
> +            sudo apt install -y ros-humble-control-msgs ros-humble-control-toolbox ros-humble-gazebo-ros2-control ros-humble-joint-state-broadcaster ros-humble-joint-state-publisher ros-humble-joint-
Corrected it!

2024-04-11 17:17 UTC, AryanNanda17 commented
I tried again in Linux and it is working now. I guess 
```ros-humble-gazebo-ros-dbgsym```
```ros-humble-gazebo-ros-pkgs```
weren't properly configured. 
![Screenshot from 2024-04-11 22-46-38](https://github.com/SRA-VJTI/MARIO/assets/125150482/c8960668-e517-4045-84e3-d81fe91e56fb)

2024-04-11 17:22 UTC, AryanNanda17 commented
For Mac:-
In robostack, this package is not available ```ros-humble-gazebo-ros-dbgsym```. And ```conda install ros-humble-gazebo-ros-pkgs``` is also giving me conflicts.

2024-04-11 17:39 UTC, aPR0T0 commented
Solve the mac errors by tomorrow, I will merge then tomorrow morning!

2024-04-12 04:31 UTC, aPR0T0 requested changes

2024-04-12 04:31 UTC, aPR0T0 commented on installations.sh
> +        cd $HOME/ros2_ws/src
where is cloning step?

2024-04-12 04:40 UTC, RapidRoger18 reviewed
Please look into suggested changes. @SuperChamp234, Can you review the suggestions.

2024-04-12 04:40 UTC, RapidRoger18 commented on installations.sh
> +if [ ! -d "$HOME/MARIO" ]; then
Using double inverted commas won't work. Make changes as per line 14 for esp folder.

2024-04-12 04:40 UTC, RapidRoger18 commented on installations.sh
> +_shell_="${SHELL#${SHELL%/*}/}"
Suggestions: I would recommend using $0 command instead of $SHELL as some systems print shell path. Instead of concatenation $0 will always give shell name only.

2024-04-12 04:40 UTC, RapidRoger18 commented on installations.sh
> +            echo "source /opt/ros/humble/setup.bash" >> $HOME/."$_shell_"rc
Since we are identifying shell for each system better to use $0 to run the a particular shell script instead of using bash.

2024-04-12 04:54 UTC, RapidRoger18 commented on installations.sh
> +!/usr/bin/env bash
If we are using bash from env why bother using $shell??

2024-04-12 06:19 UTC, aPR0T0 commented
@AryanNanda17 please go through this gist and make the [generic changes](https://gist.github.com/aPR0T0/4a2732812e2ca0469bc7e75bec676f7b])

2024-04-12 08:18 UTC, AryanNanda17 commented on installations.sh
> +if [ ! -d "$HOME/MARIO" ]; then
> Using double inverted commas won't work. Make changes as per line 14 for the esp folder.

Hello @RapidRoger18, enclosing a string in double quotes indeed does work. When you use double quotes, variables, and certain special characters within the quotes get expanded.

2024-04-12 08:19 UTC, AryanNanda17 commented on installations.sh
> +if [ ! -d "$HOME/MARIO" ]; then
Still, in order to maintain consistency, I have removed the double quotes. 
Thanks for the suggestion!

2024-04-12 10:21 UTC, AryanNanda17 commented on installations.sh
> +_shell_="${SHELL#${SHELL%/*}/}"
Thanks for the suggestion. Updated it!

2024-04-12 10:23 UTC, AryanNanda17 commented on installations.sh
> +            echo "source /opt/ros/humble/setup.bash" >> $HOME/."$_shell_"rc
Line 113 will only be executed in the case of linux, where Bash serves as the default shell.

2024-04-12 10:27 UTC, aPR0T0 commented on installations.sh
> +if [ ! -d "$HOME/MARIO" ]; then
You might have not pushed the changes @AryanNanda17 as I am unable to see removed quotes

2024-04-12 10:29 UTC, AryanNanda17 commented on installations.sh
> +!/usr/bin/env bash
When a script starts with #!/usr/bin/env bash, it tells the system to execute the script using the bash interpreter found in the environment. In this context, $0 technically represents the script's filename, not the shell being used.

2024-04-12 10:30 UTC, AryanNanda17 commented on installations.sh
> +if [ ! -d "$HOME/MARIO" ]; then
pushed now.

2024-04-12 10:32 UTC, AryanNanda17 commented on installations.sh
> +        cd $HOME/ros2_ws/src
I missed cloning it here. Thanks for pointing it out @aPR0T0.

2024-04-12 11:01 UTC, merged