Python path update and some README changes
SRA-VJTI/ROS-Workshop-2.1 pull request #72
Opened 2024-04-08 14:33 UTC by RapidRoger18

1. Python path in all python scripts updated to newer python installation path.
2. Cmakelist file changes to include forward_kinematics_module and inverse_kinematics_module in include files path.
3. README file changes in firmware/4_microros_gazebo for more clear instructions.

2024-04-09 05:49 UTC, aPR0T0 commented
@RapidRoger18 can you test this on multiple systems?

2024-04-09 13:24 UTC, aPR0T0 requested changes

2024-04-09 13:24 UTC, aPR0T0 commented on firmware/4_microros_gazebo/README.md
> +ros2 run simulation_gazebo basic_gazebo.launch.py
Its launch not run

2024-04-09 14:00 UTC, RapidRoger18 commented on firmware/4_microros_gazebo/README.md
> +ros2 run simulation_gazebo basic_gazebo.launch.py
Changes done. please check.

2024-04-09 14:26 UTC, aPR0T0 approved these changes

2024-04-09 14:26 UTC, aPR0T0 commented on 1_chatter_listener/scripts/talker.py
> +# !/usr/bin/python3
There is space here, its not consistent

2024-04-11 06:02 UTC, RapidRoger18 commented on 1_chatter_listener/scripts/talker.py
> +# !/usr/bin/python3
Changes Done

2024-04-11 06:21 UTC, merged